### ISSUE TITLE
Introduce state management within the Studio plugin

### ISSUE THREAD

**Issue by AnUnderratedPerson** [quantix-dev/verde#18]
**Affected Areas**
- [ ] Verde CLI
- [x] Verde Studio Plugin
- [ ] Verde VSC Extension

**Reason for change**
A good and easy-to-use state management framework would be best for the development of the Studio Plugin for Verde as data can be manipulated, computed, and shared easily across scripts.

**Describe the solution**
The current plugin has its interface current compiled to an RBMX file and is scripted manually with the use of no proper structure and no state management. Libraries like Vide or Fusion would provide a stateful interface that would make it easier to share and manipulate data within the studio plugin. 

**Additional context**
Vide: https://github.com/centau/vide
Fusion: https://github.com/dphfox/Fusion

**Comment by quantix-dev** [comment]
Plan on using Fusion as Vide is not in a viable state for usage in production code.

**Comment by alexzinyew** [comment]
See my fork: https://github.com/alexzinyew/verde

**Comment by alexzinyew** [comment]
also, @AnUnderratedPerson. Are you able to make toast notifications? I can't come up with a good look for them

**Comment by AnUnderratedPerson** [comment]
Sure @alexzinyew, I'll check out the initial design for the interface and see how I can make a design
