### ISSUE TITLE
[Feature]: Migrate Verde to use centau/vide

### ISSUE THREAD

**Issue by quantix-dev** [quantix-dev/verde#25]
### Area

Roblox Studio Plugin

### Describe the reason for change

Vide is a more performant UI framework and is part of the same ecosystem as Verde. I feel performance is key for Verde and having a lighter framework will make the interface feel snappier.

### Describe the solution

- [ ] Fusion will be removed as a dependency and replaced with Vide 0.1.
- [ ] Utility modules such as the theme, and store will be migrated.
- [ ] Each component will be migrated, with base components (those with the least dependents) being migrated first.
- [ ] Extensive testing will be done using an older, stable, version of the Verde plugin compared to the migrated Vide plugin to confirm parity.
- [ ] Additional improvements can be made on migrated code to fully utilise Vide's performance benefits.

This change can be separated as an individual PR so as to avoid stifling development and cluttering the synchronisation branch.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by centau** [comment]
i agree
